### ISSUE TITLE
Doesn't work with no-title-bar package

### ISSUE THREAD

**Issue by trevc** [simurai/one-vibrancy#3]
How are you removing the titlebar as shown in your screenshots? I've tried the usual no-title-bar Atom package, but it seems to disable the effect. Thanks!

**Comment by simurai** [comment]
> How are you removing the titlebar as shown in your screenshots?

That's the `hidden` option in `Settings > Core > Title Bar`:

![screen shot 2017-07-04 at 1 22 26 pm](https://user-images.githubusercontent.com/378023/27815059-4846604c-60bc-11e7-89e2-01027b62edb2.png)

But it also removes the traffic lights, so might not be ideal for everyone.

> I've tried the usual no-title-bar Atom package, but it seems to disable the effect.

The no-title-bar package would need some extra overriding in 
your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file:

```less
// Override for one-vibrancy + no-title-bar
.one-vibrancy atom-workspace-axis {
  background-color: transparent !important;
}
```
