### ISSUE TITLE
File Tree Background Color

### ISSUE THREAD

**Issue by kennetpostigo** [simurai/one-vibrancy#4]
Awesome Theme! I'm currently using nuclide that is a package on `apm` not a theme and for some reason it's file tree doesn't become "vibrant". Do you know why this may be?

![image](https://user-images.githubusercontent.com/8888991/27838136-ac1fdf4a-60b6-11e7-86a9-0735d8295d74.png)

**Comment by simurai** [comment]
Ahh.. yes, Nuclide uses their own file tree, you can add the styles below to 
your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file:

```less
// Add vibrancy to Nuclide's file tree
.one-vibrancy {
  .nuclide-file-tree-toolbar-container,
  .tree-view {
    background-color: transparent;
  }
}
```
