### ISSUE TITLE
Makes git-diff package basically useless

### ISSUE THREAD

**Issue by igor10k** [simurai/one-vibrancy#8]
`git-diff` uses colored css borders to show what was modified in the document and this line in your css makes all borders the same color.

```css
* {
  border-color: fade(@text-color-selected, 8%) !important;
}
```

Not the best idea.
